baseURL = "/"
title = "法典网 - 中国法律快查手册"
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'

theme = "hugo-book"
# enableGitInfo = true

[params]
  BookTheme = 'auto'

  BookToC = true
  BookSection = 'docs'

  BookSearch = true
  BookComments = false
  BookFlatSection = true
